version: 2
jobs:
  build-api:
    docker:
      - image: circleci/golang:1.10.2
        environment:
          DOCKER_IMAGE_NAME: nmnellis/vistio-api

    working_directory: /go/src/github.com/nmnellis/vistio
    steps:
      - checkout
      - run: cd api && make test
      - run: cd api && make build
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd api &&
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker build -t $DOCKER_IMAGE_NAME .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_IMAGE_NAME
          fi
          if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(?:\.[0-9]+){2}$ ]]; then
            docker build -t "$DOCKER_IMAGE_NAME:$CIRCLE_TAG" .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
          fi
  build-web:    
    docker:
      - image: circleci/node:10.3.0
        environment:
          DOCKER_IMAGE_NAME: nmnellis/vistio-web

    working_directory: ~/vistio
    steps:
      - checkout
      - run: cd web && npm install
      - setup_remote_docker:
          docker_layer_caching: true
      - run: |
          cd web &&
          if [ "${CIRCLE_BRANCH}" == "master" ]; then
            docker build -t $DOCKER_IMAGE_NAME .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push $DOCKER_IMAGE_NAME
          fi
          if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(?:\.[0-9]+){2}$ ]]; then
            docker build -t "$DOCKER_IMAGE_NAME:$CIRCLE_TAG" .
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push "$DOCKER_IMAGE_NAME:$CIRCLE_TAG"
          fi
workflows:
  version: 2
  build_project:
    jobs:
      - build-api
      - build-web
